### ISSUE TITLE
Performance: How expensive is computing an Oberon proof?

### ISSUE THREAD

**Issue by mwherman2000** [trinsic-id/okapi#400]
For example, if the Json representation of a Verifiable Credential is about 60 Kbytes,  
a) is it better to create (and verify) an Oberon proof based on the entire Json payload, or 
b) is it better to create (and verify) an Oberon proof of an SHA hash (for example) of the Json payload?

What is recommended?

Language in question: .NET

**Comment by mwherman2000** [comment]
I did some testing. 10,000 iterations on a small piece of Json (1398 bytes) and a larger piece (63792 bytes).  The savings of computing the Oberon proof of the SHA256 hash vs. the Oberson proof of the Json itself is between 0 and 18%.
```
json.length:    1398 bytes
iterations:     10000
hashtime:       36ms
jsonprooftime:  66396ms
hashprooftime:  66208ms
reduction:      0.2831495873245376%
```

```
json.length:    63792 bytes
iterations:     10000
hashtime:       618ms
jsonprooftime:  79359ms
hashprooftime:  64644ms
reduction:      18.54232034173817%
```

**Comment by tmarkovski** [comment]
Oberon will hash the input data before generating or verifying proofs, using the [hash to curve](https://datatracker.ietf.org/doc/draft-irtf-cfrg-hash-to-curve/) spec. This means the performance difference comes down to using smaller payload for this step. Based on your analysis, it seems there's considerable gain to pre-hash the payload, especially since VCs can be quite large. It would then make sense to use [high performance hash algorithm](https://medium.com/asecuritysite-when-bob-met-alice/for-hashing-the-fastest-of-the-fastest-meet-t1ha-bbff79ed11d0).

Are you working on a data integrity suite for VCs with Oberon signatures?

**Comment by mwherman2000** [comment]
Hi Tomis, I'm working on a potential IIW34 demo for something I call the _Secure Verifiable Credentials Transport Protocol (VSTPS)_. 

There are many different aspects to this effort but the key principle surrounds using a Verifiable Capability Authorization (VCA) as an integral property of a Verifiable Credential (VC) and that the intended receiver of a particular VC needs to receive, acknowledge, and agree to the VCA before the VC is sent to them (sort of like _self-sovereignty applied to the exchange of business documents_). A high-level view of the VCTPS DID protocol looks like this...

![vctps-protocol-sequence-diagram](https://user-images.githubusercontent.com/6101736/162749224-d1941e9b-cfa7-42cc-ac9f-3561bf46afe2.png)

The Okapi library has made the "DID" and "DIDCOMM" parts of the project extraordinarily easy to implement: `DIDKey`, `DIDPack/DIDUnpack`, `Oberon`...

There are some more details here (mostly code so far with a few diagrams): https://github.com/mwherman2000/VCTPSPrototypes/blob/main/README.md

**Comment by fundthmcalculus** [comment]
@mwherman2000 is this still an issue, or simply an academic question?
